<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">registerInvokeInterceptor</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKU3RyaW5nIGVuZHBvaW50ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1
cnNvciwgImVuZHBvaW50Iik7ClN0cmluZyBhcHBJZCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlw
ZWxpbmVDdXJzb3IsICJBcHBJRCIpOwpTdHJpbmcgc2FmZSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZWxpbmVDdXJzb3IsICJTYWZlIik7CkJvb2xlYW4gdGhyb3dFcnJvciA9IChCb29sZWFuKSBJ
RGF0YVV0aWwuZ2V0KHBpcGVsaW5lQ3Vyc29yLCAidGhyb3dFcnJvciIpOwpTdHJpbmdbXSBjb25u
ZWN0aW9ucyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShwaXBlbGluZUN1cnNvciwgImNvbm5l
Y3Rpb25zIik7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCi8vIHByb2Nlc3MKCkFycmF5TGlz
dDxTdHJpbmc+IGFsbG93ZWQgPSBuZXcgQXJyYXlMaXN0PFN0cmluZz4oKTsKSGFzaE1hcDxTdHJp
bmcsIFN0cmluZz4gYWxpYXNlcyA9IG5ldyBIYXNoTWFwPFN0cmluZywgU3RyaW5nPigpOwoKaWYg
KHRocm93RXJyb3IgPT0gbnVsbCkKCXRocm93RXJyb3IgPSB0cnVlOwoKaWYgKGNvbm5lY3Rpb25z
ICE9IG51bGwpIHsKCWZvciAoU3RyaW5nIGMgOiBjb25uZWN0aW9ucykgewoJCWlmIChjLmNvbnRh
aW5zKCI7IikpIHsKCQkJaW50IGkgPSBjLmluZGV4T2YoIjsiKTsKCQkJU3RyaW5nIGsgPSBjLnN1
YnN0cmluZygwLCBpKTsKCQkJU3RyaW5nIHYgPSBjLnN1YnN0cmluZyhpKzEpOwoJCQlhbGxvd2Vk
LmFkZChrKTsKCQkJCgkJCVN5c3RlbS5vdXQucHJpbnRsbigic2V0dGluZyB1cCBhbGlhcyAiICsg
ayArICIgPSAiICsgdik7CgkJCWFsaWFzZXMucHV0KGssIHYpOwoJCX0gZWxzZSB7CgkJCWFsbG93
ZWQuYWRkKGMpOwoJCX0KCX0KfQoKaWYgKGFsbG93ZWQuc2l6ZSgpID4gMCkgewoJQ3JlZGVudGlh
bHNJbmplY3Rvci5yZWdpc3RlcihhbGxvd2VkLnRvQXJyYXkobmV3IFN0cmluZ1thbGxvd2VkLnNp
emUoKV0pLCBuZXcgVmF1bHRDaGVja2VyKGVuZHBvaW50LCBhcHBJZCwgc2FmZSwgYWxpYXNlcyks
IHRocm93RXJyb3IpOwp9IGVsc2UgewoJQ3JlZGVudGlhbHNJbmplY3Rvci5yZWdpc3RlcihudWxs
LCBuZXcgVmF1bHRDaGVja2VyKGVuZHBvaW50LCBhcHBJZCwgc2FmZSwgYWxpYXNlcyksIHRocm93
RXJyb3IpOwp9</value>
</Values>
