<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getCyberarkProperties</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKU3RyaW5nW10gcHJvcHMgPSBy
ZWFkRmlsZUFzU3RyaW5nTGlzdChQUk9QU19GSUxFKTsKCmZvciAoU3RyaW5nIHAgOiBwcm9wcykg
ewoJCglpZiAocC5pbmRleE9mKCI9IikgIT0gLTEpIHsKCQlpbnQgaSA9IHAuaW5kZXhPZigiPSIp
OwoJCVN0cmluZyBrID0gcC5zdWJzdHJpbmcoMCwgaSk7CgkJU3RyaW5nIHYgPSBwLnN1YnN0cmlu
ZyhpKzEpOwoJCQoJCWlmIChrLmNvbnRlbnRFcXVhbHMoInRocm93RXJyb3IiKSkKCQkJSURhdGFV
dGlsLnB1dChjLCBrLCBCb29sZWFuLnBhcnNlQm9vbGVhbih2KSk7CgkJZWxzZQoJCQlJRGF0YVV0
aWwucHV0KGMsIGssIHYpOwoJfQp9CgppZiAoSURhdGFVdGlsLmdldChjLCAic3luY0ludGVydmFs
IikgPT0gbnVsbCkgewoJSURhdGFVdGlsLnB1dChjLCAic3luY0ludGVydmFsIiwgIjAiKTsKfQoK
Yy5kZXN0cm95KCk7Cgk=</value>
</Values>
