<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">tokenize</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBpbnN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVD
dXJzb3IsICJpbnN0cmluZyIpOwpTdHJpbmcgZGVsaW1pdGVyID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhwaXBlbGluZUN1cnNvciwgImRlbGltaXRlciIpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7
CgovLyBwcm9jZXNzCgpTdHJpbmcgc3RyaW5nMSA9IGluc3RyaW5nOwpTdHJpbmcgc3RyaW5nMiA9
IGluc3RyaW5nOwoKaW50IGkgPSBpbnN0cmluZy5pbmRleE9mKGRlbGltaXRlciAhPSBudWxsID8g
ZGVsaW1pdGVyIDogIjsiKTsKCmlmIChpICE9IC0xKSB7CglzdHJpbmcxID0gaW5zdHJpbmcuc3Vi
c3RyaW5nKDAsIGkpOwoJc3RyaW5nMiA9IGluc3RyaW5nLnN1YnN0cmluZyhpKzEpOwp9CgovLyBw
aXBlbGluZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJzdHJpbmcxIiwgc3Ry
aW5nMSk7CklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJzdHJpbmcyIiwgc3RyaW5nMik7
CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCgk=</value>
</Values>
